
clear;
addpath('../jsonlab'); %JSON Library


%%Load Data
data =load('vessel_data.txt');
data=data(:,2:11);          % Complete Shrinked Data

%%Maximum and Minimum Range 
minvalues= min(data);
maxvalues= max(data);


field1 = 'minvalues';
value1 = {minvalues};
field2 = 'maxvalues';
value2 = {maxvalues};

jsondata = struct(field1,value1,field2,value2);
savejson('minmaxrange',jsondata,'minmaxvalues.json');



 %% Test for including all values between minimum and maximum
id= (  data(:,1) >= minvalues(1) & data(:,1) <= maxvalues(1)         & ...
        data(:,2) >= minvalues(2) & data(:,2) <= maxvalues(2)        & ...
        data(:,3) >= minvalues(3) & data(:,3) <= maxvalues(3)        & ...
        data(:,4) >= minvalues(4) & data(:,4) <= maxvalues(4)        & ...
        data(:,5) >= minvalues(5) & data(:,5) <= maxvalues(5)        & ...
        data(:,6) >= minvalues(6) & data(:,6) <= maxvalues(6)        & ...
        data(:,7) >= minvalues(7) & data(:,7) <= maxvalues(7)        & ...
        data(:,8) >= minvalues(8) & data(:,8) <= maxvalues(8)       & ...
        data(:,9) >= minvalues(9) & data(:,9) <= maxvalues(9)        & ...
        data(:,10) >= minvalues(10) & data(:,10) <=maxvalues(10)    ...
      ) ;
  
  
%{
  
id= (  data(:,1) >=  filterdatafromuser(1,1) & data(:,1) <= filterdatafromuser(1,2)        & ...
        data(:,2) >= filterdatafromuser(2,1) & data(:,2) <= filterdatafromuser(2,2)        & ...
        data(:,3) >= filterdatafromuser(3,1) & data(:,3) <= filterdatafromuser(3,2)        & ...
        data(:,4) >= filterdatafromuser(4,1) & data(:,4) <= filterdatafromuser(4,2)        & ...
        data(:,5) >= filterdatafromuser(5,1) & data(:,5) <= filterdatafromuser(5,2)        & ...
        data(:,6) >= filterdatafromuser(6,1) & data(:,6) <= filterdatafromuser(6,2)        & ...
        data(:,7) >= filterdatafromuser(7,1) & data(:,7) <= filterdatafromuser(7,2)        & ...
        data(:,8) >= filterdatafromuser(8,1) & data(:,8) <= filterdatafromuser(8,2)        & ...
        data(:,9) >= filterdatafromuser(9,1) & data(:,9) <= filterdatafromuser(9,2)        & ...
        data(:,10)>= filterdatafromuser(10,1) & data(:,10) < filterdatafromuser(10,2)     ...
      ) ;   
  
%}  
index=find(id);

